# Global constants used by multiple files
# 	All defined by UPPER_CASE

# Scheduler constants
OPTIM_SHIFT = 4
SOFT_ERROR = 3
NO_CHANGE = 2
FATAL_ERROR_CODE = 1
SUCCESS = 0
TRAINING_SHIFT_THRESH = 2

SCHED_SAMPLE = -1
TEACHER_FORCING = -2
GREEDY_SEARCH = -3

NO_PROG_SCALE = 15
SHIFT_LB = 2

# Model constants
BATCH_SIZE = 8
EMBEDDING_SIZE = 128
EMPTY_ID = 300

# Caster constants
BLANK_ID = 0
SPACE_ID = 27
START_ID = 28
END_ID = 29

# Dataset Constants
BUFF_LIM = 256
MAX_CLIP_DUR = 2
MAX_TARGET_LEN = 5
TRAINING_TARGET_LEN = 13 * MAX_TARGET_LEN				# MUST BE LARGER THAN SPEC FRAMES

# Mel converter constants
SR = 8000