# Global constants used by multiple files
# 	All defined by UPPER_CASE

# Model constants
BATCH_SIZE = 8
EMBEDDING_SIZE = 128
STRIKE_LIM = 4
NO_PROGRESS_LIM = STRIKE_LIM * 300
EMPTY_ID = 300

# Caster constants
BLANK_ID = 0
SPACE_ID = 27
START_ID = 28
END_ID = 29

# Dataset Constants
BUFF_LIM = 256
MAX_CLIP_DUR = 3
MAX_TARGET_LEN = 5
TRAINING_TARGET_LEN = 20 * MAX_TARGET_LEN				# MUST BE LARGER THAN SPEC FRAMES

# FIND AVG LABEL LEN, STANDARD DEVIATION 

# Mel converter constants
SR = 8000